name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  test-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy-react-app:
    needs: test-react-app # This job will run only if the test job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo "Deploying to production ..."
